<div>
    <h2 class="pull-left">Orders</h2>
    <a href="/orders/new" class="btn btn-success pull-right">Create Order</a>
</div>

            


<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Order Number</th>
            <th>Customer</th>
            <th>Description</th>
            <th class="text-right">Total</th>
        </tr>
    </thead>
    <?php foreach ($this->orders as $order): ?>
    <tr>
        <td>
            <a href="/orders/view/<?= $this->escapeHtmlAttr($order['id']) ?>">
                <?= $this->escapeHtml($order['id']) ?>
            </a>
        </td>
        <td>
            <?= $this->escapeHtml($order['order_number']) ?>
        </td>
        <td>
<!--            <a href="/customers/edit/<?= $this->escapeHtmlAttr($order['customer']['id']) ?>">
            <?= $this->escapeHtml($order['customer']['name']) ?>
            </a>-->
        </td>
        <td>
            <?= $this->escapeHtml($order['description']) ?>
        </td>
        <td class="test-right">
            <?= number_format($order['total'], 2) ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>